/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryOddEvenRouteImport } from './routes/history.odd-even'
import { Route as ExamOddEvenRouteImport } from './routes/exam.odd-even'
import { Route as HistoryOddEvenIndexRouteImport } from './routes/history.odd-even.index'
import { Route as HistoryOddEvenRunIdRouteImport } from './routes/history.odd-even.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryOddEvenRoute = HistoryOddEvenRouteImport.update({
  id: '/history/odd-even',
  path: '/history/odd-even',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamOddEvenRoute = ExamOddEvenRouteImport.update({
  id: '/exam/odd-even',
  path: '/exam/odd-even',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryOddEvenIndexRoute = HistoryOddEvenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryOddEvenRoute,
} as any)
const HistoryOddEvenRunIdRoute = HistoryOddEvenRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => HistoryOddEvenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam/odd-even': typeof ExamOddEvenRoute
  '/history/odd-even': typeof HistoryOddEvenRouteWithChildren
  '/history/odd-even/$runId': typeof HistoryOddEvenRunIdRoute
  '/history/odd-even/': typeof HistoryOddEvenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam/odd-even': typeof ExamOddEvenRoute
  '/history/odd-even/$runId': typeof HistoryOddEvenRunIdRoute
  '/history/odd-even': typeof HistoryOddEvenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam/odd-even': typeof ExamOddEvenRoute
  '/history/odd-even': typeof HistoryOddEvenRouteWithChildren
  '/history/odd-even/$runId': typeof HistoryOddEvenRunIdRoute
  '/history/odd-even/': typeof HistoryOddEvenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam/odd-even'
    | '/history/odd-even'
    | '/history/odd-even/$runId'
    | '/history/odd-even/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exam/odd-even' | '/history/odd-even/$runId' | '/history/odd-even'
  id:
    | '__root__'
    | '/'
    | '/exam/odd-even'
    | '/history/odd-even'
    | '/history/odd-even/$runId'
    | '/history/odd-even/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamOddEvenRoute: typeof ExamOddEvenRoute
  HistoryOddEvenRoute: typeof HistoryOddEvenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/odd-even': {
      id: '/history/odd-even'
      path: '/history/odd-even'
      fullPath: '/history/odd-even'
      preLoaderRoute: typeof HistoryOddEvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/odd-even': {
      id: '/exam/odd-even'
      path: '/exam/odd-even'
      fullPath: '/exam/odd-even'
      preLoaderRoute: typeof ExamOddEvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/odd-even/': {
      id: '/history/odd-even/'
      path: '/'
      fullPath: '/history/odd-even/'
      preLoaderRoute: typeof HistoryOddEvenIndexRouteImport
      parentRoute: typeof HistoryOddEvenRoute
    }
    '/history/odd-even/$runId': {
      id: '/history/odd-even/$runId'
      path: '/$runId'
      fullPath: '/history/odd-even/$runId'
      preLoaderRoute: typeof HistoryOddEvenRunIdRouteImport
      parentRoute: typeof HistoryOddEvenRoute
    }
  }
}

interface HistoryOddEvenRouteChildren {
  HistoryOddEvenRunIdRoute: typeof HistoryOddEvenRunIdRoute
  HistoryOddEvenIndexRoute: typeof HistoryOddEvenIndexRoute
}

const HistoryOddEvenRouteChildren: HistoryOddEvenRouteChildren = {
  HistoryOddEvenRunIdRoute: HistoryOddEvenRunIdRoute,
  HistoryOddEvenIndexRoute: HistoryOddEvenIndexRoute,
}

const HistoryOddEvenRouteWithChildren = HistoryOddEvenRoute._addFileChildren(
  HistoryOddEvenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamOddEvenRoute: ExamOddEvenRoute,
  HistoryOddEvenRoute: HistoryOddEvenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
